name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
            apt update
            apt -y install software-properties-common make git python python-pip ditaa
            pip install -r tools/labs/requirements.txt
            cd tools/labs && make docs
    - name: Publish
      # not yet implemented
      run: env
